#!/bin/sh

username=""
password=""

if `nmcli device show | grep -q BPGC`; then
curl -d "username=$username&password=$password&mode=191" -H "Content-Type: application/x-www-form-urlencoded" -X POST https://campnet.bits-goa.ac.in:8090/login.xml
fi

